"""first migration

Revision ID: d131aadb9d62
Revises: 
Create Date: 2020-11-28 23:40:09.730284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd131aadb9d62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('abstract', sa.TEXT(), nullable=True),
    sa.Column('time', sa.VARCHAR(length=20), nullable=True),
    sa.Column('bio_id', sa.INTEGER(), nullable=True),
    sa.Column('company', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['bio_id'], ['bio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
